---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-ffc-demo-internal
  namespace: ffc-demo
spec:
  ingress:
    - action: Allow
      protocol: TCP
  egress:
    - action: Allow
      protocol: TCP