{{ if .Values.apiServer.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.apiServer.namespace.name }}
---

{{ $apiServerSpec := omit .Values.apiServer "enabled" }}
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec:
{{ $apiServerSpec | toYaml | indent 2 }}
{{ end }}